CREATE TABLE IF NOT EXISTS USERS (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(25) NOT NULL,
  email VARCHAR(35) NOT NULL,
  username VARCHAR(16) NOT NULL,
  password VARCHAR(200) NOT NULL,
  avatar VARCHAR NOT NULL DEFAULT '/static/img/defaultprofile.jpeg',
  birth_date DATE NOT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  register_date DATE NOT NULL default CURRENT_DATE,
  UNIQUE(username)
);

CREATE TABLE  IF NOT EXISTS MOVIES (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  title VARCHAR NOT NULL,
  year INTEGER NOT NULL,
  directors VARCHAR NOT NULL,
  writers VARCHAR NOT NULL,
  urlPoster VARCHAR NOT NULL,
  genres VARCHAR NOT NULL,
  idIMDB VARCHAR NOT NULL,
  plot TEXT NOT NULL,
  simpleplot TEXT NOT NULL,
  runtime VARCHAR NOT NULL,
  overallRating DOUBLE  DEFAULT 0,
  votes INTEGER NOT NULL DEFAULT 0,
  rating DOUBLE  NOT NULL,
   UNIQUE(idIMDB)
);

CREATE TABLE IF NOT EXISTS WATCHLIST(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(25) REFERENCES users(username) on delete cascade NOT NULL,
  movie_id VARCHAR(25) REFERENCES movies(idIMDB)  on delete cascade  NOT NULL,
  status INT default 0,
  watchOrder INT default 1,
  register_date DATE NOT NULL default CURRENT_DATE,
  notes VARCHAR(200) DEFAULT NULL,
  stream VARCHAR(80) DEFAULT NULL 
);

CREATE TABLE IF NOT EXISTS STARS(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  urlIMDB VARCHAR(50) NOT NULL,
  name VARCHAR(30) NOT NULL,
  knownFor VARCHAR NOT NULL,
  rating INT NOT NULL,
  user_rating INT DEFAULT 0,
  date_created DATE NOT NULL default CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS FORUMPOSTS (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(25) NOT NULL REFERENCES USERS(username) ON DELETE CASCADE,
  important int default 0,
  title VARCHAR NOT NULL,
  body VARCHAR NOT NULL,
  rep INT NOT NULL default 0,
  date_created DATE NOT NULL default CURRENT_DATE
);

CREATE TABLE  IF NOT EXISTS COMMENTS(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  thread BIGSERIAL NOT NULL REFERENCES FORUMPOSTS(id) ON DELETE CASCADE,
  username VARCHAR(25) NOT NULL REFERENCES USERS(username) ON DELETE CASCADE,
  body VARCHAR NOT NULL,
  date_created DATE NOT NULL default CURRENT_DATE
);

CREATE TABLE  IF NOT EXISTS IN_THEATERS(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  type INT DEFAULT 0, -- 0 for in theaters, 1 for incoming
  title VARCHAR,
  year INT NOT NULL,
  releaseDate DATE NOT NULL ,
  directors VARCHAR NOT NULL,
  genres  VARCHAR NOT NULL,
  simpleplot VARCHAR NOT NULL,
  rating DOUBLE  NOT NULL,
  runtime VARCHAR NOT NULL,
  urlIMDB VARCHAR NOT NULL,
  urlPoster VARCHAR NOT NULL,
  writers VARCHAR NOT NULL,
  point int DEFAULT 0,
  plike VARCHAR DEFAULT NULL 
);

CREATE TABLE IF NOT EXISTS SHOWTIMES(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  title VARCHAR NOT NULL,
  hours VARCHAR NOT NULL,
  cinema VARCHAR(20) NOT NULL,
  date VARCHAR(10) NOT NULL
);